### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by peterklijn**
Given that our team maintains the MOP project, I think it makes sense to make us code owners as well

### CODE REVIEW

**Comment by mantzas** [comment]
@peterklijn Harvester is also used in the configuration system of Matching. I could have added the Matching team as code owners also. I want to give an opportunity for other to contribute and participate in OSS inside the company.
I will be reaching out to all of our engineers to see if they might be interests.
Thanks

**Comment by peterklijn** [comment]
Ok, fair. I've updated it to only myself, as I've contributed to harvester in the past, you ok with that?

**Comment by peterklijn** [comment]
Ok, fair. I've updated it to only myself, as I've contributed to harvester in the past, you ok with that @mantzas?

**Comment by mantzas** [comment]
@peterklijn perfectly fine.

**Review by mantzas — APPROVED** [review]

**Comment by mantzas** [comment]
Closing this one since the change has been already added to master.

**Pull request closed without merging**
