### PR TITLE
Add feature for seeding from files

### PR DESCRIPTION
**Pull request by Oberonus**
## Which problem is this PR solving?

Sometimes it is needed to seed some complex data from external file, and it is not fit well in ENV variables. 

## Short description of the changes

Add `file` seeding type. When specified, file is being read and populated in the corresponding field. Behaves the same way as other seeding types. No breaking changes introduced.

### CODE REVIEW

**Comment by mantzas** [comment]
@Oberonus hi, there is a race condition detected in CI

**Comment by Oberonus** [comment]
> @Oberonus hi, there is a race condition detected in CI

It seems something flaky and unrelated... Just re-triggered the job and everything went green, may be we need to investigate deeper.

**Comment by Oberonus** [comment]
> Nice change. It would be nice if you could also add monitoring functionality to read file changes and update the configuration.

Thanks @c0nstantx, yes, there are some ideas to incorporate a watcher and probably add support for s3, but it will take some time.

**Comment by mantzas** [comment]
@c0nstantx this needs much more work and for our use case we cannot change the file inside a pod.. we have to redeploy. so this is just seeding not monitoring.
As mentioned S3 is a good candidate for doing seed and monitor.

**Comment by c0nstantx** [comment]
@mantzas As you can see, I have approved this PR since it's fine within its scope. The suggestion was for an enhancement in another PR

**Pull request merged**
